name: Test and Deploy ${{github.repository}}
run-name: ${{github.actor}} running test and deploy
on:
  pull_request:
    branches:
      - main
      - dev
jobs:
  test-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20.11.0
          cache: "pnpm"

      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 8.14.1

      - name: Checkout ${{github.ref}} repository
        uses: actions/checkout@v4
        with:
          ref: ${{github.ref}}

      - name: Install dependencies
        run: pnpm install

      - name: Run linting checks
        run: pnpm lint
